### ISSUE TITLE
Backend Database

### ISSUE THREAD

**Issue by jcho42** [fruitByTheForLoops/GraceFlopper#7]
Access products from database
- [x]  create models 
- [x]  create model associations 
- [x]  create seed.js
  - [x] explore the <trefle.io> API @Jeff-Lee-0228 
  - [x] figure out how to randomly generate reasonable prices and quantities of stock, etc. @khu-md 
- [x]  set tests

DUE by 16:30 CST 9/22/2020

**Comment by khu-md** [comment]
Regarding tests.

Names of our databases will be `fruity-seeds` and `fruity-seeds-test`. This is specified by our `package.json.name` attribute.

See `db.js` file.
